<?php

/**
 * @file
 * Install hooks for the Organigram node types kickstarter module.
 */

use Drupal\organigram_node_types_kickstarter\Installer\NodeTypesKickstarterInstaller;

/**
 * Implements hook_install().
 */
function organigram_node_types_kickstarter_install(): void {
  $installer = \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(NodeTypesKickstarterInstaller::class);
  $installer->install();
}
